package com.web.ec;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import com.web.form.LoginForm;
import com.web.model.User;
import com.web.repository.UserRepository;


@RequestMapping("/login")
@Controller
public class Login {

	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@GetMapping
	public String input(@ModelAttribute LoginForm form,Model model) {
		return "login/input";
	}

	@PostMapping
	public String result(@Validated @ModelAttribute LoginForm form, BindingResult result, Model model,RedirectAttributes attribute ) {
		if (result.hasErrors()) {
			return input(form,model);
		}
		System.out.println(form.getLoginId());
		System.out.println(form.getPassword());

		List<User> user = (List<User>) userRepository.findByLoginIdAndPassword(form.getLoginId(),form.getPassword());
		if(user.size()==0) {
			attribute.addFlashAttribute("msg", "loginIdかpasswordに誤りがあります");
			return "redirect:/login";
		}else {

			model.addAttribute("loginUser", user.get(0));
		    return "login/index";
	    }

	}






}
